### ISSUE TITLE
Issue during install on OS X (El Capitan) with Meteor 1.2.1

### ISSUE THREAD

**Issue by tomthebuzz** [perak/kitchen-site#218]
Hi Petar,

can't seem to get past the install. Tried both the CURL and the manual approach. Always get an issue once I reach the copyfiles:

**Issue extract from terminal:**

sudo curl http://www.meteorkitchen.com/install | /bin/sh
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2148    0  2148    0     0   5989      0 --:--:-- --:--:-- --:--:--  6000
Installing "Meteor Kitchen" - Meteor application code generator
Detecting OS...
Detected OS: Darwin
Downloading distribution...
######################################################################## 100,0%
Unpacking...
../bin/meteor-kitchen: Path contains '..'
../examples/: Path contains '..'
../examples/example-accounts/: Path contains '..'
../examples/example-admin/: Path contains '..'
../examples/example-dataview/: Path contains '..'
...
....
../templates/code/server_simple.js: Path contains '..'
../templates/code/string_utils.js: Path contains '..'
tar: copyfile unpack (../templates/ui/bootstrap3/bootstrap3-plugins/.DS_Store) failed: No such file or directory
tar: copyfile unpack (../templates/ui/bootstrap3/.DS_Store) failed: No such file or directory
tar: copyfile unpack (../templates/ui/bootstrap3-raw/bootstrap3-less/.DS_Store) failed: No such file or directory
tar: copyfile unpack (../templates/ui/bootstrap3-raw/.DS_Store) failed: No such file or directory
tar: copyfile unpack (../templates/ui/.DS_Store) failed: No such file or directory
tar: copyfile unpack (../templates/.DS_Store) failed: No such file or directory
tar: Error exit delayed from previous errors.

**Comment by perak** [comment]
@tomthebuzz oops! Somehow .DS_store files are included into package... I'll upload correct version 1-2 hours after now

**Comment by perak** [comment]
@tomthebuzz fixed! (and tested on El Capitan).

**Comment by perak** [comment]
@tomthebuzz OK, fixed now.

**Comment by tomthebuzz** [comment]
Thx @perak  - works smoothly now.

**Comment by perak** [comment]
:+1:

**Comment by vfonsecapv** [comment]
Hi guys, I still have the same problem with OSX Install. The URL http:// is wrong in the bash file.

**Comment by perak** [comment]
@vfonsecapv fixed.
